name: Azure Login

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CERTIFICATE }}
            enable-AzPSSession: true
            auth-type: service-principal
      - name: Azure CLI script
            az login --service-principal --username "2494145e-875c-437a-aabb-c3df4e1a6a6e" --tenant "72f988bf-86f1-41af-91ab-2d7cd011db47"--password ${{ secrets.AZURE_CERTIFICATE }}

      - name: Run Azure CLI command
        run: az account show